<h1>Show All Employees in our Company</h1>
<table>
    <thead>
        <tr>
            <th scope="col">Employee SSN</th>
            <th scope="col">Last Name</th>
            <th scope="col">First Name</th>
        </tr>
    </thead>
    <tbody>

        <?php foreach ($this->entries as $entry): ?>
            <tr>
                <td><a href="<?php echo $this->url(array('controller' => 'EmpView'), 'default', true) ?>"><?php echo $this->escape($entry->ssn) ?></a></td>
                <td><?php echo $this->escape($entry->lname) ?></td>
                <td><?php echo $this->escape($entry->fname) ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

