<h1>Projects of the Company</h1>
<table>
    <thead>
        <tr>
            <th scope="col">Project Number</th>
            <th scope="col">Project Name</th>
        </tr>
    </thead>
    <tbody>

        <?php foreach ($this->entries as $entry): ?>
            <tr>
                <td><a href="<?php echo $this->url(array('controller' => 'ProjView'), 'default', true) ?>"><?php echo $this->escape($entry->pnumber) ?></a></td>
                <td><?php echo $this->escape($entry->pname) ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

